export const  skills = [
  {
    title: "Python",
    icon: "lucide:code",
    description: "Expert level proficiency",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "JavaScript",
    icon: "lucide:file-code",
    description: "Frontend & backend development",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "React.js",
    icon: "lucide:globe",
    description: "UI Library",
    colSpan: 2,
    rowSpan: 2,
  },
  {
    title: "SQL",
    icon: "lucide:database",
    description: "Database",
    colSpan: 2,
    rowSpan: 2,
  },
  {
    title: "C++",
    icon: "lucide:terminal",
    description: "Systems programming",
    colSpan: 2,
    rowSpan: 2,
  },
  {
    title: "Node.js",
    icon: "lucide:server",
    description: "Backend development",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "UI/UX Design",
    icon: "lucide:tv",
    description: "Interface design & prototyping",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "AI & Machine Learning",
    icon: "lucide:git-branch",
    description: "Model development & deployment",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "Next.js",
    icon: "lucide:code",
    description: "React framework",
    colSpan: 3,
    rowSpan: 2,
  },
];