export const skills = [
  {
    title: "Python",
    icon: "lucide:code",
    description: "Aprendizaje activo",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "JavaScript",
    icon: "lucide:file-code",
    description: "Frontend & Backend",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "React.js",
    icon: "lucide:globe",
    description: "Interfaces de usuario",
    colSpan: 2,
    rowSpan: 2,
  },
  {
    title: "SQL",
    icon: "lucide:database",
    description: "Gestión de BD",
    colSpan: 2,
    rowSpan: 2,
  },
  {
    title: "C++",
    icon: "lucide:terminal",
    description: "Lógica de sistemas",
    colSpan: 2,
    rowSpan: 2,
  },
  {
    title: "Node.js",
    icon: "lucide:server",
    description: "Arquitectura de servidor",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "UI/UX Design",
    icon: "lucide:tv",
    description: "Diseño y prototipado",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "IA y Machine Learning",
    icon: "lucide:git-branch",
    description: "Desarrollo y despliegue de modelos",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "Next.js",
    icon: "lucide:code",
    description: "Framework basado en React",
    colSpan: 3,
    rowSpan: 2,
  },
];