export const skills = [
  {
    title: "Symfony",
    icon: "fa-brands:symfony",
    description: "Aprendizaje Activo",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "Docker",
    icon: "lucide:box",
    description: "Desarrollo & Despliegue",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "SQL",
    icon: "lucide:database",
    description: "Gestión de BD",
    colSpan: 2,
    rowSpan: 2,
  }, 
  {
    title: "React.js",
    icon: "lucide:globe",
    description: "Interfaces de usuario",
    colSpan: 2,
    rowSpan: 2,
  },  
  {
    title: "C++",
    icon: "lucide:terminal",
    description: "Lógica de sistemas",
    colSpan: 2,
    rowSpan: 2,
  },
  {
    title: "JavaScript",
    icon: "lucide:file-code",
    description: "Frontend & Backend",
    colSpan: 3,
    rowSpan: 2,
  },  
  {
    title: "Node.js",
    icon: "lucide:server",
    description: "Arquitectura de servidor",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "UI/UX Design",
    icon: "lucide:tv",
    description: "Diseño & prototipado",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "Automatización",
    icon: "lucide:robot",  
    description: "Procesos Organizacionales",
    colSpan: 3,
    rowSpan: 2,
  },
   
];