export const skills = [
  {
    title: "Symfony",
    icon: "fa-brands:symfony",
    subtitle: "Aprendizaje Activo",
    description: "Framework PHP para crear páginas web interactivas, modernas y responsivas, con arquitectura sólida y escalable.",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "Docker",
    icon: "lucide:box",
    subtitle: "Desarrollo & Despliegue",
    description: "Contenerización y despliegue eficiente de aplicaciones, asegurando entornos consistentes y portables.",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "SQL",
    icon: "lucide:database",
    subtitle: "Gestión de BD",
    description: "Lenguaje para gestión robusta y consultas eficientes en bases de datos relacionales.",
    colSpan: 2,
    rowSpan: 2,
  },
  {
    title: "React.js",
    icon: "lucide:globe",
    subtitle: "Interfaces de usuario",
    description: "Biblioteca para construir interfaces de usuario dinámicas, rápidas y reutilizables en aplicaciones web.",
    colSpan: 2,
    rowSpan: 2,
  },
  {
    title: "C++",
    icon: "lucide:terminal",
    subtitle: "Lógica de sistemas",
    description: "Lenguaje poderoso para desarrollo de sistemas, lógica avanzada y aplicaciones de alto rendimiento.",
    colSpan: 2,
    rowSpan: 2,
  },
  {
    title: "JavaScript",
    icon: "lucide:file-code",
    subtitle: "Frontend & Backend",
    description: "Lenguaje de programación versátil para desarrollo frontend y backend, creando experiencias web interactivas.",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "Node.js",
    icon: "lucide:server",
    subtitle: "Arquitectura de servidor",
    description: "Entorno de ejecución para JavaScript en servidor, ideal para construir APIs rápidas y escalables.",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "UI/UX Design",
    icon: "lucide:tv",
    subtitle: "Diseño & prototipado",
    description: "Diseño centrado en el usuario para crear interfaces intuitivas y experiencias atractivas.",
    colSpan: 3,
    rowSpan: 2,
  },
  {
    title: "Automatización",
    icon: "mage:robot-uwu-fill",
    subtitle: "Procesos Organizacionales",
    description: "Implementación de procesos automatizados para optimizar flujos de trabajo y aumentar la eficiencia.",
    colSpan: 3,
    rowSpan: 2,
  },
];
